### PR TITLE
Sse

### PR DESCRIPTION
**Pull request by lukepow**
Changed websocket server to use server sent events:
 - Import  http module to create server.
 - Add content type of "text/event-stream".
 - Emit the changes received by the pg subscriber
 - Add event listener to admin file to accept data from text stream

### CODE REVIEW

**Review by sarahvoshall — APPROVED** [review]
Event server looks great. 

Did you mean to push eventserver/.env? 
Also I understand that you're sending events to admin to test functionality, but eventually, the events will not be looped back to the admin but sent to client apps right?

**Review by timw-csi — CHANGES_REQUESTED** [review]
- looks good for most part, but same q’s as sash. Thanks Luke
- `eventserver/package.json` has old info in Description in line 4, can be deleted
- `docker-compose.yaml` lines 74 – 78 can be deleted.
	- noticed you changeed restart to ‘always’ from ‘unless-stopped’. What’s reason behind that?

**Review by timw-csi — APPROVED** [review]
nice one, looks great!

**Review by MattLui — APPROVED** [review]
LG 🔥

**Review by sarahvoshall — APPROVED** [review]
🚢

**Pull request merged**
