### PR TITLE
updated eventserver & admin images

### PR DESCRIPTION
**Pull request by sarahvoshall**
Update the event server to serve 2 routes
  - GET / for the healthcheck
  - GET /realtime for connecting to the SSE stream

Update the admin server img to use the new /realtime route for the EventSource

updated event server image is version 3.0.1 https://hub.docker.com/repository/docker/snowclone/eventserver/general
updated admin image is version 2.0.1 https://hub.docker.com/repository/docker/snowclone/admin/general

### CODE REVIEW

**Review by MattLui — COMMENTED** [review]
New images work for me 🔥 
Couple of questions:

1. On line 6 of .gitignore you added eventserver/.env; did you use a .env file to build the latest event server? Previously, I did not have one as I believe the environment variables are stored in the docker-compose file and it worked fine.
2. On line 56 of admin/Dockerfile should that CMD be uncommented? Think we were looking at that this morning and confused why it was commented out.

**Comment by sarahvoshall** [comment]
The .env was just for testing locally. 

Good catch on the Dockerfile -- the current admin image is _not_ running in prod mode.

**Comment by timw-csi** [comment]
Ok cool, thanks for merging main into this branch to bring it up to date, Sash.  

Re admin/Dockerfile: do we want to change that before approving this PR and merging into main? Or good to go?

**Comment by sarahvoshall** [comment]
if it aint broke...

**Review by timw-csi — APPROVED** [review]
nice work, gang. We'll put a pin in coming back to lline 56 of admin/Dockerfile

Could be a good thing to mark our shift from 'dev' to 'prod'

**Pull request merged**
