### PR TITLE
fix: new images uploaded with AMD64 platform for compatibility

### PR DESCRIPTION
**Pull request by MattLui**
Images should now be compatible across devices.

### CODE REVIEW

**Comment by sarahvoshall** [comment]
Also pushed commits for updating the event server to provide two routes: 
  - GET / for the ECS healthcheck
  - GET /realtime for listening for db changes

And updated the docker-compose.yaml file to use the new (linux/amd64) image of the above https://hub.docker.com/repository/docker/sashvosh/event-server/general

**Comment by MattLui** [comment]
Thanks, @sarahvoshall . For consistency can you please push your event-server image to our group dockerhub:
`docker login` (enter username and password for snowclone)
`docker build --platform linux/amd64 -t snowclone/eventserver:2.0.0 .`
`docker push snowclone/eventserver:2.0.0`

And then docker-compose can pull from that image: `snowclone/eventserver:2.0.0`

**Comment by sarahvoshall** [comment]
just pushed changes! https://hub.docker.com/repository/docker/snowclone/eventserver/general

**Comment by timw-csi** [comment]
I am going to close this PR and we can figure out in our EoD our best next steps. Probably will be separating them back into two PRs.

**Pull request closed without merging**
