### PR TITLE
chore: moved environment variables from docker-compose to .env

### PR DESCRIPTION
**Pull request by MattLui**
- All environment variables now housed in .env
- Changed our default API token from "helo" to "blizzard" to inject some snowclone flavor; feel free to change it!

### CODE REVIEW

**Review by timw-csi — COMMENTED** [review]
Wow, so much cleaner in the docker-compose! Nice one.

Might be helpful to put some comments labeling each section inside the .env file so we know what variables belong to what service. That'll make it easier for our end user to know what changes they are making for security.

**Comment by timw-csi** [comment]
Also, I think it'd be nice to refactor eventserver.js so it uses the same connection string  (`DATABASE_URL` ) as the schema-server. I can do that in a separate branch.

**Comment by MattLui** [comment]
> Wow, so much cleaner in the docker-compose! Nice one.
> 
> Might be helpful to put some comments labeling each section inside the .env file so we know what variables belong to what service. That'll make it easier for our end user to know what changes they are making for security.

Great idea just pushed those labels

**Comment by MattLui** [comment]
> Also, I think it'd be nice to refactor eventserver.js so it uses the same connection string (`DATABASE_URL` ) as the schema-server. I can do that in a separate branch.

Sounds good, separate branch seems appropriate. Thanks!

**Review by timw-csi — APPROVED** [review]
Righteous

**Pull request merged**
