### PR TITLE
feat: swagger-ui

### PR DESCRIPTION
**Pull request by MattLui**
swagger-ui service added to docker-compose file and now available on port 8081 of localhost.

### CODE REVIEW

**Review by timw-csi — CHANGES_REQUESTED** [review]
nice one, Matt. Glad you got us some points on the board while we've been locked in the AWS stalemate :)

 I don't think we need the old .env files from the `server` dir and the `wsserver` dir. And I think `wsserver` dir was renamed to `eventtserver`. on line 26 of `docker-compose.yaml` it looks like we are adding a duplicate `PGRST_OPENAPI_SERVER_PROXY_URI` entry.

**Comment by MattLui** [comment]
Thanks, @timw-csi ! Pushed with requested changes.

**Review by timw-csi — APPROVED** [review]
Nice one! Great work

**Review by sarahvoshall — APPROVED** [review]
🚢

**Review by lukepow — APPROVED** [review]
Nice job Matt! And nice catches, Tim

**Pull request merged**
